import type { Metadata } from "next";
// import localFont from "next/font/local";
import "../styles/globals.css";
import "../styles/styles.css";
import AppProvider from "@/layouts/StoreProvider";
import { locales } from "@/i18n/i18n.config";
// import { notFound } from 'next/navigation';
// const codecPro = localFont({
//   src: "./fonts/CodecPro-Regular.ttf",
//   variable: "--font-codecpro",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
type Props = {
  children: React.ReactNode;
};

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default async function RootLayout({ children }: Props) {
  return <AppProvider>{children}</AppProvider>;
}
